image: node:10.18.0-alpine3.10
cache:
    paths:
        - node_modules/
before_script:
    - yarn config set registry https://registry.npm.taobao.org/
    - yarn
stages:
    - lint
lint-job:
    stage: lint
    script:
        - yarn lint:style
        - yarn lint:script
    tags:
        - student-1
